### ISSUE TITLE
from utils import _get_word_ngrams

### ISSUE THREAD

**Issue by arnold-em** [tuananhphan97vn/HeterGraphLongSum#1]
hello sir
there is no utils package
maybe you miss some pakcages
could you add this package?
thank you
cht
best,

**Comment by arnold-em** [comment]
thanks ，this problem i solved，
but the tensor size 100 dont match
is there some code you may not change ，which you get from HeterGraphSum..
in HeterGrapgSum used glove.42B.300d.txt
but use 100d ， the error is 300 not match 100 d



At 2022-11-22 23:05:00, "tuananhphan97vn" ***@***.***> wrote:

thank you for your comment. Can you try remove this line (it may be a redundant code and the system still run even when ignore it) and rerun the program?

**Comment by RIU-13** [comment]
There is no function named _get_word_ngrams, but it is used to gain oracles. How did you solve them? I find generating oracles really difficult
